### ISSUE TITLE
Swiping A View Programmatically

### ISSUE THREAD

**Issue by bk207004** [modocache/MDCSwipeToChoose#18]
Im trying to swipe a View Programmatically but [self.swipeToChooseView mdc_swipe:MDCSwipeDirectionLeft]; has not been working.Am i doing something wrong?

**Comment by iujlaki** [comment]
Hi,
When I call mdc_swipe: the card just disappear and not animated with the given direction.
I use custom view.
Thanks.

**Comment by kong707** [comment]
I got exactly the same problem

**Comment by jrmgx** [comment]
Thank you, it solved my problem too,
I guess that code should be added to the project, I don't think it's the case for now
(using cocoapods updated today)
