### ISSUE TITLE
Programmatic mcd_swipe

### ISSUE THREAD

**Issue by varatep** [modocache/MDCSwipeToChoose#34]
Should clarify in the docs that the user has to manually call ```wasChosenWithDirection``` when using the mdc_swipe function on the MDCSwipeToChooseView.

In my case, the front card view would not be removed either.
Here's a basic sample of getting it to work:
```
[self.frontCardView mdc_swipe:MDCSwipeDirectionLeft];
[self.frontCardView removeFromSuperview];
[self view:self.swipeView wasChosenWithDirection:MDCSwipeDirectionLeft];
```

```
[self.frontCardView mdc_swipe:MDCSwipeDirectionRight];
[self.frontCardView removeFromSuperview];
[self view:self.swipeView wasChosenWithDirection:MDCSwipeDirectionRight];
```

**Comment by nickoneill** [comment]
Sounds like the module can't correctly determine which side of the screen the item should be swiped to. I had a similar issue when using constraints for my items. Eventually I settled on doing a quick animation to move the constraints so the item passes the swipe threshold, then triggering the swipe programmatically which was able to complete the rest of the actions (including calling wasChosenWithDirection).
