### ISSUE TITLE
When delegate forbids a choice, the view won't return to initial state

### ISSUE THREAD

**Issue by stkhapugin** [modocache/MDCSwipeToChoose#39]
**What I'd expect:**

returning `NO` from 

```objc
- (BOOL)view:(UIView *)view shouldBeChosenWithDirection:(MDCSwipeDirection)direction;
```

would throw the view to its initial state.

**What actually happens:**

view remains in the same position as it was after last dragging.

**Workaround**

manually call `mdc_returnToOriginalCenter`.

**Suggested solution**
Since `mdc_returnToOriginalCenter` is private, I think it'd be great to either make it public or modify `mdc_exitSuperviewFromTranslation` in the following manner:

```objc
    if ([delegate respondsToSelector:@selector(view:shouldBeChosenWithDirection:)]) {
        BOOL should = [delegate view:self shouldBeChosenWithDirection:direction];
        if (!should) {
            [self mdc_returnToOriginalCenter]; //< added
            return;
        }
```

(note that it now includes a call to `mdc_returnToOriginalCenter`)

Another problem is that you'd need to hack around to restore the view's state in this case, i.e. if you were overlaying something on top of the view, no appropriate callbacks will be called. It seems like adding `onCancel` block property to accompany `MDCSwipeOptions`'s `onPan` and `onChosen` would be a viable solution and won't get anyone into compatibility troubles. 

I would provide a PR if you agree that this is a problem and my solution will be good enough.

BTW, thanks for saving us a few hours of work with this thing! :)

**Comment by modocache** [comment]
I think the code snippet above, in which you call `[self mdc_returnToOriginalCenter]`, is the right solution. I also agree about adding an `onCancel` callback.

Thanks! :+1:

**Comment by acegreen** [comment]
I'm wondering how you handle the overlay self mdc_returnToOriginalCenter just returns the view to oringal center as expected but the overlay remains at alpha = 1.0
