### ISSUE TITLE
LikeOrNope in swift

### ISSUE THREAD

**Issue by rjburdish** [modocache/MDCSwipeToChoose#41]
I have implemented MDCSwipeToChoose into a swift project and have the view controller currently swiping, however I am having alot of trouble getting the graphics down and loading the stack as it is done in likeornope.. Is there any chance there is a swift version of likeornope available or will one be coming soon. I think I speak for many new IOS developers by saying this would be extremely useful.

Thanks,
Rich

**Comment by datomnurdin** [comment]
No response?

**Comment by modocache** [comment]
I'd love to include an example written in Swift, but I don't have much time to write one myself. @vikmeup? :pray:

**Comment by rjburdish** [comment]
I've actually already created a swift version which behaves the same. I'm new to GitHub, how can I submit it for other people to use? @modocache

**Comment by vikmeup** [comment]
@modocache that's perfect. I just pulled @takecian changes with Swift example.
https://github.com/modocache/MDCSwipeToChoose/pull/30

I will add Swift project of LikeOrNope this weekend.

**Comment by vikmeup** [comment]
@rjburdish feel free to fork https://github.com/modocache/MDCSwipeToChoose repo and send us pull request. 
Take a look at `https://help.github.com/articles/using-pull-requests/`

**Comment by rjburdish** [comment]
@modocache @vikmeup 

Done. I have pushed and created a pull request for my swift version of LikedOrNope and called it SwiftLikedOrNope. The README has also been updated. 

Thanks!

**Comment by vikmeup** [comment]
@rjburdish good job! I merged your pull request!
