### ISSUE TITLE
Animation for Liked and Nope button does not work

### ISSUE THREAD

**Issue by kong707** [modocache/MDCSwipeToChoose#42]
When user tap Liked or Nope button . The action works correctly except that the frontView is completely disappear without any animation . How can I solve this ?  The example app works just fine .But when I use it  on my project ,it does not work.

**Comment by kong707** [comment]
Here is the warning i got 
 <Error>: CGAffineTransformInvert: singular matrix.

**Comment by kong707** [comment]
I found out the problem. But have not found the solution yet.
in - (void)mdc_rotateForTranslation:rotationDirection:
After calling this line to specify that view has to be rotated 
self.transform = CGAffineTransformRotate(self.mdc_viewState.originalTransform,
                                             rotationDirection * rotation);

The self.frame.size changed to CGZero.  Not sure why this is happening.  In my app,  I have customed the ChoosePeopleView in the example to display only image.  This might be the cause of problem.

**Comment by kong707** [comment]
self.mdc_viewState.originalTransform always return zero matrix because it was not initiated properly. 
Putting      self.mdc_viewState.originalTransform = self.transform;
in  - (void)mdc_swipeToChooseSetup:(MDCSwipeOptions *)options 
Solved my problem.

**Comment by modocache** [comment]
@kong707 Thanks! Could you submit a pull request with the change that got things working for you? :pray:

**Comment by kong707** [comment]
@modocache  Done.  Thanks for this module as well.
