### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by modocache** [modocache/MDCSwipeToChoose#48]
Looks like the Travis CI build is failing: https://travis-ci.org/modocache/MDCSwipeToChoose/builds/54823755

The error message is strange: `Reason: The run destination iPad 2 is not valid for Testing the scheme 'MDCSwipeToChoose'.`

**Comment by vikmeup** [comment]
@modocache I will look in to that tonight, I think it's just configuration of travis-ci has to be configured, because latest changes does not affect this.

**Comment by modocache** [comment]
Awesome, thanks! :bouquet:

**Comment by vikmeup** [comment]
@modocache fixed.
https://github.com/modocache/MDCSwipeToChoose/pull/54

Sorry for delay.
