### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by confile** [modocache/MDCSwipeToChoose#62]
Running the Swift example: SwiftLikedOrNope I get the following error while:

```
fatal error: unexpectedly found nil while unwrapping an Optional value
````
 
The error is reported in class ChoosePersonView: MDCSwipeToChooseView Line 43

```
self.imageView.image = self.person.Image!
```

**Comment by vikmeup** [comment]
Fixed: https://github.com/modocache/MDCSwipeToChoose/pull/64

**Comment by confile** [comment]
Thanks!
