### ISSUE TITLE
Use MDCRGB8Bit prefix/suffix for UIColor colorWith8BitRed:green:blue:alpha method

### ISSUE THREAD

**Issue by varkor** [modocache/MDCSwipeToChoose#97]
This method name is a common-enough choice that it conflicts with other pods (e.g. [HexColors](https://github.com/mRs-/HexColors)), causing undefined behaviour and breaking various functionality. Please rename it to something unique so these issues can be avoided.

(This could well apply to other methods, but it was this one in particular that caused me problems.)

**Comment by modocache** [comment]
Agreed! It should be prefixed with `mdc_`, like the other category methods in this library.
